[package]
name = "stark-v"
version = "0.1.0"
edition = "2024"

[dependencies]
stark-v-sdk = { git = "https://github.com/AntoineFONDEUR/stark-v", rev = "f7cb8bc045118654afbe77f85c0b7e6c73ab2f9b" }

# Workspace
criterion = { workspace = true }
clap = { workspace = true }
utils = { workspace = true }
ere-zkvm-interface = { workspace = true }
bincode = { workspace = true }

[[bench]]
name = "sha256"
harness = false

[[bin]]
name = "sha256_mem_stark_v"
path = "src/bin/sha256_mem.rs"
